import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Body from "@/src/components/common/Body";
import { PropsWithChildren } from "react";

const roboto = Roboto({
  variable: "--roboto",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--robotoCondensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${robotoCondensed.variable} antialiased`}
    >
      <head></head>
      <Body>{children}</Body>
    </html>
  );
}
